version: "3.5"
services:
  nats:
    image: nats:2.10.12
    ports:
      - "4221:4222"
      - "8222:8222"
    volumes:
      - ./jet.conf:/jet.conf
    command: "-c /jet.conf --cluster nats://0.0.0.0:6222 --http_port 8222 --routes=nats-1://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
  nats-1:
    image: nats:2.10.12
    ports:
      - "4222:4222"
    volumes:
      - ./jet1.conf:/jet.conf
    command: "-c /jet.conf --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats:2.10.12
    ports:
      - "4223:4222"
    volumes:
      - ./jet2.conf:/jet.conf
    command: "-c /jet.conf --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
networks:
  nats:
    name: nats
